# -*- coding: utf-8 -*-
"""Superstore_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e0eKUxKBm9IJxerffYZF_jBORCkCDNxk

#NOW FOCUS ON THE PROJECT
"""

import pandas as pd

df = pd.read_csv('Superstore.csv', encoding='latin1')

df.isnull().sum()

df.isnull().sum()



df.columns



df['Month'] = pd.to_datetime(df['Order Date']).dt.month

df['Year'] = pd.to_datetime(df['Order Date']).dt.year

df.to_csv("Clean_Superstore", index=False)











